url: 
baseurl: 

# Site settings
title: TNRJ Ltd
email: your-email@domain.com
description: "We are a London based Agile Consultancy.  Experts in all things agile, from helping Developers and Architects with Agile solutions and practises, to guiding the enterprise through a transition to be more Agile"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Terrence Joe
  pic: 1
  position: Agile Consultant
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty